Rscript correlateHismods_global.R

Rscript drawHismodDistributions.R
Rscript drawHismodDistributions_celltype_specific.R

Rscript checkHismodNumbers_topn_intervals.R
Rscript plotHismods_above_95th.R

Rscript checkHismodNumbers_celltype_specific.R
Rscript plotHismods_above_95th.celltype_specific.R

./getHismodIntersectionStats_extend2KB.sh
Rscript getHismodIntersectionStats.R

./getHismodIntersectionStats_celltype_specific_extend2K.sh
Rscript getHismodIntersectionStats_celltype_specific.R

./getTFIntersectionStats.sh
Rscript getTFIntersectionStats.R
